name: masterclass_final_app
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # UI
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  cupertino_icons: ^1.0.2

  # Network
  http: ^1.1.0

  # Utils
  get_it: ^7.6.0
  url_launcher: ^6.1.12
  either_dart: ^1.0.0

  # Cache
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.2
  mocktail: ^1.0.0
  mocktail_image_network: ^1.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/
     - assets/icons/